### ISSUE TITLE
Application isn't routing in v0.2.4 & v0.2.5

### ISSUE THREAD

**Issue by NovaXeros** [winneon/neutron#2]
![image](https://cloud.githubusercontent.com/assets/7218338/26199508/2a59649a-3bc2-11e7-8c1e-7675c7a68655.png)

As per attached screenshot, routing never begins with the app only ever displaying ??? for multiple sections.

Have tried jumping out and back into the "next system" target, which is also the first target in the route, but even though the Location updates on the app, the routing never takes place.

Issue is present in v0.2.5 and v0.2.4, but not v0.2.3 which progresses the route no matter whether or not you have entered the system it advises you travel to.

**Comment by win0na** [comment]
The router displays ??? when EDSM doesn't know the coordinates of the system you're in, so it finds the closest system that it knows that's near you and tells you to go there before routing starts. However, once you actually reach that system, routing should start, and that's the real issue here. I'll look into this. Thanks for letting me know.

**Comment by win0na** [comment]
I'm very confused as to why this is happening, as I'm unable to reproduce this. Could you try v0.2.5 plot to a different destination from a different starting point and see if it still happens?

**Comment by NovaXeros** [comment]
Sorry for the late delay, family problems meant I was out of town over the weekend.

I've just tried out the new version (0.2.8 at time of writing) and the error now appears to be fully resolved.

Closing ticket, thanks.
